require 'rubygems'
require 'rake'

begin
  require 'jeweler'
  Jeweler::Tasks.new do |gem|
    gem.name = "ironnails"
    gem.summary = %Q{IronNails brings rails like development to IronRuby and WPF}
    gem.description = %Q{IronNails is a framework inspired by the Rails and rucola frameworks. It offers a rails-like way of developing
applications with IronRuby and Windows Presentation Foundation (WPF).}
    gem.email = "ivan@flanders.co.nz"
    gem.homepage = "http://github.com/casualjim/ironnails"
    gem.authors = ["Ivan Porto Carrero"]
    gem.add_development_dependency "rspec", ">= 0"
    gem.files = FileList["[A-Z]*", "{lib}/**/*"]
    # gem is a Gem::Specification... see http://www.rubygems.org/read/chapter/20 for additional settings
  end
  Jeweler::GemcutterTasks.new
rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: gem install jeweler"
end

desc "Build the helpers project"
task :helpers do
  puts "Building the helpers project"
  system "msbuild /clp:ErrorsOnly;WarningsOnly /nologo ../IronNails.Library/IronNails.Library.csproj"
end

desc "Cleans and builds the helpers project"
task :rebuild_helpers do
  puts "Reuilding the helpers project"
  system "msbuild /clp:ErrorsOnly;WarningsOnly  /t:Clean /nologo ../IronNails.Library/IronNails.Library.csproj"
end
